// apps/tauri-controls-solid/src/tauri-controls/components/button.tsx
import { splitProps, type ComponentProps } from "solid-js"
import { twMerge } from "tailwind-merge"

export function Button(props: ComponentProps<"button">) {
  const [local, otherProps] = splitProps(props, ["class", "children"])
  return (
    <button
      class={twMerge(
        "inline-flex cursor-default items-center justify-center",
        local.class
      )}
      {...otherProps}
    >
      {local.children}
    </button>
  )
}

// src/component/ui/Button.tsx
import { cn } from "src/lib/utils"

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  className?: string
}

export function Button({ className, ...props }: ButtonProps) {
  return (
    <button
      className={cn("items-center justify-center inline-flex", className)}
      {...props}
    ></button>
  )
}
