// apps/tauri-controls-solid/src/tauri-controls/components/button.tsx
import { splitProps, type ComponentProps } from "solid-js"
import { twMerge } from "tailwind-merge"

export function Button(props: ComponentProps<"button">) {
  const [local, otherProps] = splitProps(props, ["class", "children"])
  return (
    <button
      class={twMerge(
        "inline-flex cursor-default items-center justify-center",
        local.class
      )}
      {...otherProps}
    >
      {local.children}
    </button>
  )
}

// src/tauri-controls/components/button.tsx
import type { ButtonHTMLAttributes } from "react"
import { cn } from "src/tauri-controls/libs/utils"

export function Button({
  className,
  children,
  ...props
}: ButtonHTMLAttributes<HTMLButtonElement>) {
  return (
    <button
      className={cn(
        "inline-flex cursor-default items-center justify-center",
        className
      )}
      {...props}
    >
      {children}
    </button>
  )
}
