// apps/tauri-controls/src/tauri-controls/window-titlebar.tsx
import type { OsType } from "@tauri-apps/plugin-os"
import { useEffect, useState } from "react"
import { cn } from "src/tauri-controls/libs/utils"
import { getOsType } from "./libs/plugin-os"
import type { WindowTitlebarProps } from "./types"
import { WindowControls } from "./window-controls"

export function WindowTitlebar({
  children,
  controlsOrder = "system",
  className,
  windowControlsProps,
  ...props
}: WindowTitlebarProps) {
  const [osType, setOsType] = useState<OsType | undefined>(undefined)

  useEffect(() => {
    getOsType().then((type) => {
      setOsType(type)
    })
  }, [])

  const left =
    controlsOrder === "left" ||
    (controlsOrder === "platform" &&
      windowControlsProps?.platform === "macos") ||
    (controlsOrder === "system" && osType === "Darwin")

  const customProps = (ml: string) => {
    if (windowControlsProps?.justify !== undefined) return windowControlsProps

    const {
      justify: windowControlsJustify,
      className: windowControlsClassName,
      ...restProps
    } = windowControlsProps || {}
    return {
      justify: false,
      className: cn(windowControlsClassName, ml),
      ...restProps,
    }
  }

  return (
    <div
      className={cn(
        "bg-background flex select-none flex-row overflow-hidden",
        className
      )}
      data-tauri-drag-region
      {...props}
    >
      {left ? (
        <>
          <WindowControls {...customProps("ml-0")} />
          {children}
        </>
      ) : (
        <>
          {children}
          <WindowControls {...customProps("ml-auto")} />
        </>
      )}
    </div>
  )
}

// apps/tauri-controls-vue/src/tauri-controls/WindowTitlebar.vue
<script setup lang='ts'>
import { twMerge } from 'tailwind-merge';
import WindowControls from './WindowControls.vue';
import type { WindowTitlebarProps, WindowControlsProps } from './types';
import { getOsType } from './utils/os';
import { onMounted, ref } from 'vue';
import type { OsType } from '@tauri-apps/plugin-os';

const { controlsOrder, windowControlsProps } = withDefaults(defineProps<WindowTitlebarProps>(), {
    controlsOrder: "system",
})

const osType = ref<OsType | undefined>(undefined)

onMounted(() => {
    getOsType().then((type) => {
        osType.value = type
    })
})

const left =
    controlsOrder === "left" ||
    (controlsOrder === "platform" &&
        windowControlsProps?.platform === "macos") ||
    (controlsOrder === "system" && osType.value === "Darwin")

const customProps = (ml: string) => {
    if (windowControlsProps?.justify !== undefined)
        return windowControlsProps

    const {
        justify: windowControlsJustify,
        className: windowControlsClassName,
        ...restProps
    } = windowControlsProps || {}
    return {
        justify: false,
        className: twMerge(windowControlsClassName, ml),
        ...restProps,
    } as WindowControlsProps
}
</script>

<template>
    <div :class="twMerge('bg-background flex select-none flex-row overflow-hidden', $attrs.class as string)" data-tauri-drag-region>
        <template v-if="left">
            <WindowControls :="customProps('ml-0')" />
            <slot />
        </template>
        <template v-else>
            <slot />
            <WindowControls :="customProps('ml-auto')" />
        </template>
    </div>
</template>
