// packages/solid/src/WindowTitlebar.tsx
import { createMemo, mergeProps, splitProps, type ComponentProps } from "solid-js"
import { cn, detectPlatform, styles, type WindowTitlebarProps } from "@tauri-controls/core"
import { WindowControls } from "./WindowControls"

export function WindowTitlebar(props: WindowTitlebarProps & ComponentProps<"div">) {
  const [local, otherProps] = splitProps(props, [
    "children", "controlsOrder", "class", "windowControlsProps",
  ])

  const platform = createMemo(() => detectPlatform())

  const left = createMemo(() => {
    if (local.controlsOrder === "left") return true
    if (local.controlsOrder === "right") return false
    if (local.controlsOrder === "platform") {
      return (local.windowControlsProps?.platform ?? platform()) === "macos"
    }
    return platform() === "macos"
  })

  const windowControlsProps = mergeProps(local.windowControlsProps, {
    justify: false,
    get class() {
      return cn(local.windowControlsProps?.className, left() ? "ml-0" : "ml-auto")
    },
  })

  const controlsEl = <WindowControls {...windowControlsProps} />

  return (
    <div class={cn(styles.titlebar, local.class)} data-tauri-drag-region {...otherProps}>
      {left() ? [controlsEl, local.children] : [local.children, controlsEl]}
    </div>
  )
}

// packages/react/src/WindowTitlebar.tsx
import { useEffect, useState, type HTMLProps } from "react"
import {
  cn,
  detectPlatform,
  styles,
  type WindowTitlebarProps,
  type Platform,
} from "@tauri-controls/core"
import { WindowControls } from "./WindowControls"

export function WindowTitlebar({
  children,
  controlsOrder = "system",
  className,
  windowControlsProps,
  ...props
}: WindowTitlebarProps & Omit<HTMLProps<HTMLDivElement>, keyof WindowTitlebarProps>) {
  const [platform, setPlatform] = useState<Platform>("windows")

  useEffect(() => {
    setPlatform(detectPlatform())
  }, [])

  const left =
    controlsOrder === "left" ||
    (controlsOrder === "platform" &&
      windowControlsProps?.platform === "macos") ||
    (controlsOrder === "system" && platform === "macos")

  const controlsProps = {
    ...windowControlsProps,
    justify: false,
    className: cn(windowControlsProps?.className, left ? "ml-0" : "ml-auto"),
  }

  return (
    <div
      className={cn(styles.titlebar, className)}
      data-tauri-drag-region
      {...props}
    >
      {left ? (
        <>
          <WindowControls {...controlsProps} />
          {children}
        </>
      ) : (
        <>
          {children}
          <WindowControls {...controlsProps} />
        </>
      )}
    </div>
  )
}
