// packages/svelte/src/WindowTitlebar.svelte
<script lang="ts">
  import { onMount } from "svelte"
  import type { Snippet } from "svelte"
  import {
    cn,
    detectPlatform,
    styles,
    type Platform,
    type WindowTitlebarProps,
  } from "@tauri-controls/core"
  import WindowControls from "./WindowControls.svelte"

  let {
    controlsOrder = "system",
    windowControlsProps = undefined,
    class: className = "",
    children,
  }: {
    controlsOrder?: WindowTitlebarProps["controlsOrder"]
    windowControlsProps?: WindowTitlebarProps["windowControlsProps"]
    class?: string
    children?: Snippet
  } = $props()

  let platform: Platform = $state("windows")

  onMount(() => {
    platform = detectPlatform()
  })

  let left = $derived(
    controlsOrder === "left" ||
    (controlsOrder === "platform" && windowControlsProps?.platform === "macos") ||
    (controlsOrder === "system" && platform === "macos")
  )

  let controlsClass = $derived(cn(windowControlsProps?.className, left ? "ml-0" : "ml-auto"))
</script>

<div class={cn(styles.titlebar, className)} data-tauri-drag-region>
  {#if left}
    <WindowControls {...windowControlsProps} justify={false} class={controlsClass} />
    {#if children}{@render children()}{/if}
  {:else}
    {#if children}{@render children()}{/if}
    <WindowControls {...windowControlsProps} justify={false} class={controlsClass} />
  {/if}
</div>

// packages/react/src/WindowTitlebar.tsx
import { useEffect, useState, type HTMLProps } from "react"
import {
  cn,
  detectPlatform,
  styles,
  type WindowTitlebarProps,
  type Platform,
} from "@tauri-controls/core"
import { WindowControls } from "./WindowControls"

export function WindowTitlebar({
  children,
  controlsOrder = "system",
  className,
  windowControlsProps,
  ...props
}: WindowTitlebarProps & Omit<HTMLProps<HTMLDivElement>, keyof WindowTitlebarProps>) {
  const [platform, setPlatform] = useState<Platform>("windows")

  useEffect(() => {
    setPlatform(detectPlatform())
  }, [])

  const left =
    controlsOrder === "left" ||
    (controlsOrder === "platform" &&
      windowControlsProps?.platform === "macos") ||
    (controlsOrder === "system" && platform === "macos")

  const controlsProps = {
    ...windowControlsProps,
    justify: false,
    className: cn(windowControlsProps?.className, left ? "ml-0" : "ml-auto"),
  }

  return (
    <div
      className={cn(styles.titlebar, className)}
      data-tauri-drag-region
      {...props}
    >
      {left ? (
        <>
          <WindowControls {...controlsProps} />
          {children}
        </>
      ) : (
        <>
          {children}
          <WindowControls {...controlsProps} />
        </>
      )}
    </div>
  )
}
