// apps/tauri-controls-svelte/src/lib/WindowControls.svelte
<script lang="ts">
  import { osType } from "$lib/utils/os"
  import { cn } from "$lib/utils/utils"
  import Gnome from "./controls/linux/Gnome.svelte"
  import MacOs from "./controls/MacOs.svelte"
  import Windows from "./controls/Windows.svelte"

  export let platform = "windows"
  export let hide = false
  export let hideMethod = "display"
  export let justify = false

  const customClass = cn(
    "flex",
    $$props.class,
    hide && (hideMethod === "display" ? "hidden" : "invisible")
  )

  // Determine the default platform based on the operating system if platform not specified
  if (!platform) {
    switch (osType) {
      case "Darwin":
        platform = "macos"
        break
      case "Linux":
        platform = "gnome"
        break
      default:
        platform = "windows"
    }
  }
</script>

{#if platform === "windows"}
  <Windows {...$$props} class={cn(customClass, justify && "ml-auto")} />
{:else if platform === "macos"}
  <MacOs {...$$props} class={cn(customClass, justify && "ml-0")} />
{:else if platform === "gnome"}
  <Gnome {...$$props} class={cn(customClass, justify && "ml-auto")} />
{:else}
  <Windows {...$$props} class={cn(customClass, justify && "ml-auto")} />
{/if}

// apps/tauri-controls/src/tauri-controls/window-controls.tsx
import { useEffect, useState } from "react"
import { cn } from "src/tauri-controls/libs/utils"
import { TauriAppWindowProvider } from "./contexts/plugin-window"
import { Gnome, MacOS, Windows } from "./controls"
import { getOsType } from "./libs/plugin-os"
import type { WindowControlsProps } from "./types"

export function WindowControls({
  platform,
  justify = false,
  hide = false,
  hideMethod = "display",
  // linuxDesktop = "gnome",
  className,
  ...props
}: WindowControlsProps) {
  const [osType, setOsType] = useState<string | undefined>(undefined)

  useEffect(() => {
    getOsType().then((type) => {
      setOsType(type)
    })
  }, [])

  const customClass = cn(
    "flex",
    className,
    hide && (hideMethod === "display" ? "hidden" : "invisible")
  )

  // Determine the default platform based on the operating system if not specified
  if (!platform) {
    switch (osType) {
      case "Darwin":
        platform = "macos"
        break
      case "Linux":
        platform = "gnome"
        break
      default:
        platform = "windows"
    }
  }

  const ControlsComponent = () => {
    switch (platform) {
      case "windows":
        return (
          <Windows
            className={cn(customClass, justify && "ml-auto")}
            {...props}
          />
        )
      case "macos":
        return (
          <MacOS className={cn(customClass, justify && "ml-0")} {...props} />
        )
      case "gnome":
        return (
          <Gnome className={cn(customClass, justify && "ml-auto")} {...props} />
        )
      default:
        return (
          <Windows
            className={cn(customClass, justify && "ml-auto")}
            {...props}
          />
        )
    }
  }

  return (
    <TauriAppWindowProvider>
      <ControlsComponent />
    </TauriAppWindowProvider>
  )
}
