// apps/tauri-controls/src/tauri-controls/window-controls.tsx
import { useEffect, useState } from "react"
import { cn } from "src/tauri-controls/libs/utils"
import { TauriAppWindowProvider } from "./contexts/plugin-window"
import { Gnome, MacOS, Windows } from "./controls"
import { getOsType } from "./libs/plugin-os"
import type { WindowControlsProps } from "./types"

export function WindowControls({
  platform,
  justify = false,
  hide = false,
  hideMethod = "display",
  // linuxDesktop = "gnome",
  className,
  ...props
}: WindowControlsProps) {
  const [osType, setOsType] = useState<string | undefined>(undefined)

  useEffect(() => {
    getOsType().then((type) => {
      setOsType(type)
    })
  }, [])

  const customClass = cn(
    "flex",
    className,
    hide && (hideMethod === "display" ? "hidden" : "invisible")
  )

  // Determine the default platform based on the operating system if not specified
  if (!platform) {
    switch (osType) {
      case "Darwin":
        platform = "macos"
        break
      case "Linux":
        platform = "gnome"
        break
      default:
        platform = "windows"
    }
  }

  const ControlsComponent = () => {
    switch (platform) {
      case "windows":
        return (
          <Windows
            className={cn(customClass, justify && "ml-auto")}
            {...props}
          />
        )
      case "macos":
        return (
          <MacOS className={cn(customClass, justify && "ml-0")} {...props} />
        )
      case "gnome":
        return (
          <Gnome className={cn(customClass, justify && "ml-auto")} {...props} />
        )
      default:
        return (
          <Windows
            className={cn(customClass, justify && "ml-auto")}
            {...props}
          />
        )
    }
  }

  return (
    <TauriAppWindowProvider>
      <ControlsComponent />
    </TauriAppWindowProvider>
  )
}

// apps/tauri-controls-solid/src/tauri-controls/window-controls.tsx
import { Match, mergeProps, onMount, splitProps, Switch } from "solid-js"
import { twMerge } from "tailwind-merge"
import { Gnome, MacOS, Windows } from "./controls"
import { getOsType } from "./libs/plugin-os"
import type { WindowControlsProps } from "./types"

export function WindowControls(props: WindowControlsProps) {
  const [rawLocal, otherProps] = splitProps(props, [
    "class",
    "hideMethod",
    "hide",
    "platform",
    "justify"
  ])

  const local = mergeProps(
    {
      justify: false,
      hide: false,
      hideMethod: "display"
    },
    rawLocal
  )

  onMount(() => {
    getOsType().then((type) => {
      if (!local.platform) {
        switch (type) {
          case "Darwin":
            local.platform = "macos"
            break
          case "Linux":
            local.platform = "gnome"
            break
          default:
            local.platform = "windows"
        }
      }
    })
  })

  const customClass = twMerge(
    "flex",
    local.class,
    local.hide && (local.hideMethod === "display" ? "hidden" : "invisible")
  )

  // Determine the default platform based on the operating system if not specified
  return (
    <Switch
      fallback={
        <Windows
          class={twMerge(customClass, local.justify && "ml-auto")}
          {...otherProps}
        />
      }
    >
      <Match when={local.platform === "windows"}>
        <Windows
          class={twMerge(customClass, local.justify && "ml-auto")}
          {...otherProps}
        />
      </Match>
      <Match when={local.platform === "macos"}>
        <MacOS
          class={twMerge(customClass, local.justify && "ml-0")}
          {...otherProps}
        />
      </Match>
      <Match when={local.platform === "gnome"}>
        <Gnome
          class={twMerge(customClass, local.justify && "ml-auto")}
          {...otherProps}
        />
      </Match>
    </Switch>
  )
}
